version: "3.9"

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine
  
  discountdb:
    image: postgres:15-alpine
  
  pgadmin:
    image: dpage/pgadmin4
  
  portainer:
    image: portainer/portainer-ce
  
  catalogservice:
    build:
      context: ./src/Microservices
      dockerfile: CatalogService.Dockerfile
      
  basketservice:
    build:
      context: ./src/Microservices
      dockerfile: BasketService.Dockerfile
  
  discountservice:
    build:
      context: ./src/Microservices
      dockerfile: DiscountService.Dockerfile
  
  discountgrpcservice:
    build:
      context: ./src/Microservices
      dockerfile: DiscountGrpcService.Dockerfile
      
volumes:
  mongo_data:
  postgres_data:
  portainer_data:
  pgadmin_data:
