version: "3.9"

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27016:27017"
    volumes:
      - mongo_data:/data/db
  
  catalogservice:
    container_name: catalogservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:6000
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:6000"
       
      